### ISSUE TITLE
about the roi align backprop

### ISSUE THREAD

**Issue by GriffithKQ** [CharlesShang/FastMaskRCNN#116]
i can not find the backprop step in the  all the packages, especially i examined the crop.py where seems like the roialign and find nothing. does any one find it ? if we do not have this layer , the result should not be coverage

**Comment by animebing** [comment]
@GriffithKQ, the roi align is implemented in the return statement of function `crop_` in `libs/layers/crop.py` as below 
```python
    return  [tf.image.crop_and_resize(images, boxes, batch_inds,
                                         [pooled_height, pooled_width],
                                         method='bilinear',
                                         name='Crop')] + [boxes]
```
here I mean `tf.image.crop_and_resize`, so I think the back propagation is done by tensorflow
