### ISSUE TITLE
EigenAllocator for GPU ran out of memory when allocating 0

### ISSUE THREAD

**Issue by souryuu** [CharlesShang/FastMaskRCNN#15]
Has anyone encountered this error ?

`Starting training...`
`: I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libcupti.so.8.0 locally`
`: E tensorflow/core/common_runtime/bfc_allocator.cc:244] tried to allocate 0 bytes`
`: W tensorflow/core/common_runtime/allocator_retry.cc:32] Request to allocate 0 bytes`
`: F tensorflow/core/common_runtime/gpu/gpu_device.cc:103] EigenAllocator for GPU ran out of memory when allocating 0. See error logs for more detailed info. `
`Aborted (core dumped)`

I found the error after running  `python test/resnet50_test.py` in the docker container with the following set up.

platform : Ubuntu 16.04.2 LTS
Cuda: 8.0, V8.0.61
nvidia driver version : 367.48 
tf version : 1.0.1
GPU : GTX1080

**Comment by Sharathnasa** [comment]
@souryuu I'm facing this issue. What did you do to get rid of this? Could you please help me.

Regards,
Sharath
