### ISSUE TITLE
confused about the mask_targets implementation

### ISSUE THREAD

**Issue by brisker** [CharlesShang/FastMaskRCNN#156]
In the original paper,
 "the mask target is the intersection between an RoI and its associated ground-truth mask." . 
But it seems that the code here: https://github.com/CharlesShang/FastMaskRCNN/blob/master/libs/layers/mask.py#L73-L76
 **just use the associated ground-truth mask,** **not the intersection between an RoI and its associated ground-truth mask, as the "mask_target".** So is there any bug in the code , or have I understand something wrong?
@CharlesShang

**Comment by brisker** [comment]
I am wrong, closing this.

**Comment by chenguanfu511** [comment]
I am also wondering this? I see the code is get the roi crop from the target mask.
![image](https://user-images.githubusercontent.com/7610009/57963980-b3636380-795f-11e9-868d-0f53de982029.png)
