### ISSUE TITLE
Installation on Windows Command line error D8021 : invalid numeric argument '/Wno-cpp'

### ISSUE THREAD

**Issue by Westerby** [CharlesShang/FastMaskRCNN#173]
Specs:
Windows 10
Python 3.6,1

When running python setup.py build_ext --inplace I get error: 

cl : Command line error D8021 : invalid numeric argument '/Wno-cpp'
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

I would appreciate any help.

**Comment by ScNico** [comment]
You can  replace  extra_compile_args=['-Wno-cpp', '-Wno-unused-function', '-std=c99'] with extra_compile_args={'gcc': ['/Qstd=c99']} in ./libs/datasets/pycocotools/setup.py. maybe help

**Comment by Westerby** [comment]
Super, it worked. Thanks!

**Comment by ruizengalways** [comment]
mark

**Comment by ghost** [comment]
How did you determine @ScNico which flags were the issue though?

**Comment by ghost** [comment]
I'm having similar issues on a totally different project, trying to build in QT-Creator a wallet for a cryptocurrency, but only ever works cross-compiled on linux for windows, or on linux.

**Comment by siba36** [comment]
how can i replace extra_compile_args ?? @ScNico
