### ISSUE TITLE
Missing licence

### ISSUE THREAD

**Issue by petrbel** [CharlesShang/FastMaskRCNN#2]
Under what license is the code distributed?

I propose creating a LICENSE file specifying it (probably MIT?).

Thanks for the implementation - great work!

**Comment by CharlesShang** [comment]
Thank you for your suggestion. 
Since this repo reuses many code by others, I want people use it freely.
And I have no ideas about license :-)  Just create a Apache License since it is the first license on the list.

**Comment by CharlesShang** [comment]
Just googled it.
Apache License and MIT are roughly the same, but with more constrains. 
I'll switch to MIT.

**Comment by bhack** [comment]
You can reuse (or collaborate) also with different components or GPU ops already implemented in https://github.com/endernewton/tf-faster-rcnn that is under MIT

**Comment by petrbel** [comment]
great, thanks
