### ISSUE TITLE
冒昧向作者请教一个RCNN的收敛速度问题

### ISSUE THREAD

**Issue by mttbx** [CharlesShang/FastMaskRCNN#213]
@CharlesShang 
你好，我有个问题想请教下，知道你很忙，但是还是想问一下，我自己写了一个MASK-RCNN类似的网络结构，我发现RCNN的收敛速度比SSD慢了好几倍，我经过分析发现RPN的box loss震荡的非常厉害，导致了这个问题。你遇到过这个问题吗，如果遇到过能请教下是怎么解决这个问题的吗？非常感谢。

**Comment by mttbx** [comment]
问题已经解决了，但是还有个训练速度很慢的问题，这个后面再优化就是了

**Comment by jiangwqcooler** [comment]
Is he Chinese？
Are you OK?
What's your problem?

**Comment by 300LiterPropofol** [comment]
请问这个问题产生的原因是什么?您是怎么解决的?
