### ISSUE TITLE
Fresher with working RCNN

### ISSUE THREAD

**Issue by thisismihir** [CharlesShang/FastMaskRCNN#215]
Sorry for asking such a naive question, but I am a complete fresher in this. 
So, as mentioned downloaded the same repository on my windows 10. 
And on my command propmt, I entered the command: "python setup.py" and I got an error saying: "No module named Cython. Build".
Can someone help me with that, please?

**Comment by rye36** [comment]
Hi,
Not sure whether you would of already fixed this bit you need to pip install Cython
