### ISSUE TITLE
Number of BaseAnchors equals 15?

### ISSUE THREAD

**Issue by maxenceliu** [CharlesShang/FastMaskRCNN#29]
In the FPN paper, there are totally 15 anchors in the pyramid. But in this code, there are 15 anchors in each layer of the pyramid？ Do I understand right?

**Comment by xmyqsh** [comment]
@maxenceliu 
You are right.
> we define the an- chors to have areas of {322 , 642 , 1282 , 2562 , 5122 } pixels on {P2, P3, P4, P5, P6} respectively.1 As in [28] we also use anchors of multiple aspect ratios {1:2, 1:1, 2:1} at each level. So in total there are 15 anchors over the pyramid.

**Comment by CharlesShang** [comment]
In PFN, a layer in pyramid corresponds only ONE scale of anchors. 
[C2 -- 32x32, C3 -- 64x64, ... ] 
Here, I use 15 anchors for each layer. I'll improve that if the experient look worse.

**Comment by zacwellmer** [comment]
Any updates on the experiment?
