### ISSUE TITLE
Inconsistent bounding box comparison in roi.py

### ISSUE THREAD

**Issue by souryuu** [CharlesShang/FastMaskRCNN#48]
I just found bug that might be crucial to the training performance.

When the gt_boxes and rois are compared for overlapping bbox in roi.py, the location of gt_boxes is always located outside of the image_width and image_height. 

> restored previous model ./output/mask_rcnn/coco_resnet50_model.ckpt-10000 from ./output/mask_rcnn/
gt_boxes, all_rois_boxes, image_height, image_width
[ 323.63354492  620.6907959   519.75689697  853.        ]
[ 471.59197998  637.71154785  479.          639.        ]
640
480
iter 0: image-id:0511854, time:2.907(sec), regular_loss: 0.045890, total-loss 0.3424(0.0201, 0.1604, 0.013625, 0.1309, 0.0174), instances: 6, batch:(32|143, 29|116, 29|29)
gt_boxes, all_rois_boxes, image_height, image_width
[  84.42687988  156.66087341  743.39923096  437.59051514]
[ 579.50476074  501.31628418  639.          505.        ]
506
640
gt_boxes, all_rois_boxes, image_height, image_width
[ 204.19114685  302.1496582   639.75        853.        ]
[ 371.91244507  496.81021118  374.          499.        ]
500
375
iter 1: image-id:0118642, time:0.503(sec), regular_loss: 0.045887, total-loss 0.1679(0.0218, 0.0755, 0.003574, 0.0446, 0.0224), instances: 3, batch:(2|34, 5|69, 5|5)
gt_boxes, all_rois_boxes, image_height, image_width
[ 777.29266357  414.71099854  959.25054932  584.87304688]
[ 635.87683105  421.24139404  639.          426.        ]
427
640
iter 2: image-id:0369299, time:1.459(sec), regular_loss: 0.045884, total-loss 0.2647(0.0216, 0.2318, 0.000000, 0.0113, 0.0000), instances: 11, batch:(44|186, 0|64, 0|0)
gt_boxes, all_rois_boxes, image_height, image_width
[ 419.12524414  254.65420532  744.14953613  595.51403809]
[ 627.88568115  425.22784424  639.          427.        ]
428
640
iter 3: image-id:0118644, time:0.584(sec), regular_loss: 0.045881, total-loss 0.2346(0.0158, 0.1414, 0.004386, 0.0530, 0.0200), instances: 2, batch:(2|34, 7|71, 7|7)
gt_boxes, all_rois_boxes, image_height, image_width
[ 510.07662964  413.48086548  579.43835449  428.32342529]
[ 635.88970947  373.29919434  639.          375.        ]
376
640
iter 4: image-id:0191625, time:1.247(sec), regular_loss: 0.045879, total-loss 0.1773(0.0076, 0.1624, 0.000000, 0.0074, 0.0000), instances: 6, batch:(8|56, 0|64, 0|0)
gt_boxes, all_rois_boxes, image_height, image_width
[ 673.07409668  325.83309937  870.11651611  601.65960693]
[ 635.88812256  423.82373047  639.          428.        ]
429
640
iter 5: image-id:0511866, time:0.901(sec), regular_loss: 0.045877, total-loss 0.1991(0.0065, 0.1242, 0.005354, 0.0449, 0.0182), instances: 5, batch:(20|104, 7|71, 7|7)

**Comment by souryuu** [comment]
To solve this, you need to edit get_dataset function in dataset_factory.py. Output new_ih and new_iw after preprocessing instead of ih and iw.

**Comment by amirbar** [comment]
I think you are right. Although I think we shouldn't change the code in dataset_factory.
i.e - in test time we would need the original height and width to reshape the image (and apply the inverse transformation to the predictions) back to the original size.
