### ISSUE TITLE
when i run train.py:  W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Input to reshape is a tensor with 1 values, but the requested shape has 0

### ISSUE THREAD

**Issue by tjussh** [CharlesShang/FastMaskRCNN#60]
when i run the train.py, it occurs an error as follows：
 
iter 143: image-id:0347794, time:0.350(sec), regular_loss: 0.202597, total-loss 0.7763(0.0430, 0.3557, 0.000000, 0.3776, 0.0000), instances: 2, batch:(2|34, 0|64, 0|0)
iter 144: image-id:0478967, time:0.364(sec), regular_loss: 0.202596, total-loss 1.5152(0.0312, 0.3461, 0.007214, 0.4630, 0.6678), instances: 6, batch:(18|88, 13|77, 13|13)
iter 145: image-id:0478903, time:0.338(sec), regular_loss: 0.202596, total-loss 1.4753(0.0226, 0.3851, 0.002755, 0.3975, 0.6674), instances: 1, batch:(1|33, 4|68, 4|4)
**2017-05-23 14:28:53.840796: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Input to reshape is a tensor with 1 values, but the requested shape has 0**
	 [[Node: Reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](DecodeRaw_1/_555, Reshape/shape)]]
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Input to reshape is a tensor with 1 values, but the requested shape has 0
	 [[Node: Reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](DecodeRaw_1/_555, Reshape/shape)]]
	 [[Node: ReverseV2/_599 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_277_ReverseV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
iter 146: image-id:0522233, time:0.361(sec), regular_loss: 0.202596, total-loss 0.7871(0.0609, 0.3661, 0.000000, 0.3601, 0.0000), instances: 5, batch:(22|101, 0|64, 0|0)
Traceback (most recent call last):
  File "/home/JKe/sunshihua/Program/pycharm/helpers/pydev/pydev_run_in_console.py", line 78, in <module>
    globals = run_file(file, None, None)
  File "/home/JKe/sunshihua/Program/pycharm/helpers/pydev/pydev_run_in_console.py", line 35, in run_file
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/JKe/sunshihua/FastMaskRCNN-master/train/train.py", line 225, in <module>
    train()
  File "/home/JKe/sunshihua/FastMaskRCNN-master/train/train.py", line 221, in train
    coord.join(threads)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 237, in _run
    enqueue_callable()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1063, in _single_operation_run
    target_list_as_strings, status, None)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 1 values, but the requested shape has 0
	 [[Node: Reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](DecodeRaw_1/_555, Reshape/shape)]]
	 [[Node: ReverseV2/_599 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_277_ReverseV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
Process finished with exit code 1

Someone has any idea?

**Comment by ElementLi** [comment]
@tjussh any update?

**Comment by zhangleiedu** [comment]
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 1 values, but the requested shape has 0

Someone has any idea? thanks

**Comment by yuanCnD** [comment]
the same error as you did when i used pycharm. Using terminal can figure out. I think before run trian.py, you should make sure ran  run download_and_convert_data.py have no error and #50 is helpful.

**Comment by qmzpg** [comment]
I get this problem too, have you fixed it?

**Comment by AndrewKemendo** [comment]
I fixed this error by reverting to tensorflow 1.1.0-gc

**Comment by yuye1992** [comment]
i have the same problem  with tensorflow 1.3.Did you solved it?
