### ISSUE TITLE
cpu only compile

### ISSUE THREAD

**Issue by sosong** [CharlesShang/FastMaskRCNN#62]
when I compile ./libs as in the step 4 in the "how to", there is a error ,"EnvironmentError: The nvcc binary could not be located in your $PATH. Either add it to your path, or set $CUDAHOME" .  I know i didn't have a cuda card, can I build in the cpu only mode? any one can give some advice？ thanks.

**Comment by ddlricardo** [comment]
I solved this problem, just annotate these code in ./bin/setup.py:

CUDA = locate_cuda()

self.set_executable('compiler_so', CUDA['nvcc'])


And then delete these code:

Extension(
        'nms.gpu_nms',
        ['nms/nms_kernel.cu', 'nms/gpu_nms.pyx'],
        library_dirs=[CUDA['lib64']],
        libraries=['cudart'],
        language='c++',
        runtime_library_dirs=[CUDA['lib64']],
        # this syntax is specific to this build system
        # we're only going to use certain compiler args with nvcc and not with gcc
        # the implementation of this trick is in customize_compiler() below
        extra_compile_args={'gcc': ["-Wno-unused-function"],
                            'nvcc': ['-arch=sm_52',
                                     '--ptxas-options=-v',
                                     '-c',
                                     '--compiler-options',
                                     "'-fPIC'"]},
        include_dirs = [numpy_include, CUDA['include']]
    ),

Then you can make successfully.

**Comment by thundertrick** [comment]
@ddlricardo Have u met this error?
Annotating those codes did solve the making problem, but when running `python train/train.py`, the script may not found `gpu_nms` module:

~~~
Traceback (most recent call last):
  File "train/train.py", line 21, in <module>
    import libs.nets.pyramid_network as pyramid_network
  File "train/../libs/nets/pyramid_network.py", line 10, in <module>
    from libs.layers import anchor_encoder
  File "train/../libs/layers/__init__.py", line 9, in <module>
    from .wrapper import anchor_decoder
  File "train/../libs/layers/wrapper.py", line 13, in <module>
    from . import sample
  File "train/../libs/layers/sample.py", line 9, in <module>
    import libs.boxes.nms_wrapper as nms_wrapper
  File "train/../libs/boxes/nms_wrapper.py", line 10, in <module>
    import libs.nms.gpu_nms as gpu_nms
ImportError: No module named gpu_nms
~~~

**Comment by jurastm** [comment]
@ddlricardo it worked for me. Thank you.

**Comment by zhang-yw** [comment]
@thundertrick May I ask you how you solved the new problem? Thanks.

**Comment by VasanthBalakrishnan** [comment]
@thundertrick : Just replace the gpu_nms implementation by the CPU version in libs/boxes/nms_wrapper.py.

- Comment the gpu_nms import in line 10.

- Change line 18 ( return statement of def nms(...) ) from 
`    return gpu_nms.gpu_nms(dets, thresh, device_id=0)
`
to
`    return cpu_nms.cpu_nms(dets, thresh)
`

**Comment by WKChung1028** [comment]
It is work. Thank you
