### ISSUE TITLE
After training the model, how to load the weights and predict ? 

### ISSUE THREAD

**Issue by abduallahmohamed** [CharlesShang/FastMaskRCNN#70]
Currently I'm training the model and planning to share the weights if it worked out ! I'm using K80 GPU for this, but I've a question after training the model, how to load the weights and predict ? 

Can you write down a code sample ?

**Comment by abduallahadel** [comment]
@CharlesShang  ?

**Comment by Jiakui** [comment]
can you share your weight to us? thanks

**Comment by abduallahadel** [comment]
Here's the weights of epoch 190K, 

https://drive.google.com/file/d/0BwVrmnQ5PwycT0p1Y0tLQV9UYUk/view?usp=sharing , 
can you share the code for testing ?

**Comment by Fanping** [comment]
Can any body share the code for prediction?
