### ISSUE TITLE
HELP When I run 'train.py': ValueError: string_input_producer requires a non-null input tensor

### ISSUE THREAD

**Issue by lileiNPU** [CharlesShang/FastMaskRCNN#71]
I have no idea about how to deal with it.

runfile('/home/daxika/FastMaskRCNN-master/train/train.py', wdir='/home/daxika/FastMaskRCNN-master/train')
Traceback (most recent call last):

  File "<ipython-input-1-9faf080c9a79>", line 1, in <module>
    runfile('/home/daxika/FastMaskRCNN-master/train/train.py', wdir='/home/daxika/FastMaskRCNN-master/train')

  File "/home/daxika/anaconda2/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "/home/daxika/anaconda2/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py", line 94, in execfile
    builtins.execfile(filename, *where)

  File "/home/daxika/FastMaskRCNN-master/train/train.py", line 222, in <module>
    train()

  File "/home/daxika/FastMaskRCNN-master/train/train.py", line 114, in train
    is_training=True)

  File "/home/daxika/FastMaskRCNN-master/train/../libs/datasets/dataset_factory.py", line 16, in get_dataset
    image, ih, iw, gt_boxes, gt_masks, num_instances, img_id = coco.read(tfrecords)

  File "/home/daxika/FastMaskRCNN-master/train/../libs/datasets/coco.py", line 98, in read
    tfrecords_filename, num_epochs=100)

  File "/home/daxika/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/input.py", line 213, in string_input_producer
    raise ValueError(not_null_err)

ValueError: string_input_producer requires a non-null input tensor

**Comment by tjussh** [comment]
I think maybe is your working directory is wrong. Try to change to "/home/daxika/FastMaskRCNN-master". I hope it works.

**Comment by lymrty** [comment]
this may be because the function coco.read(tfrecords), cann't find the data of *.tfrecords

**Comment by lileiNPU** [comment]
@lymrty
Yes, you are right. I have modified the code. But there have some new errors. I am working on them.

**Comment by xingbowei** [comment]
I have the same problem, I don't know how to solve it now, can you tell me how you solved it? thank you

**Comment by lileiNPU** [comment]
I have solved the error. Modify the code in 'dataset_factory.py'. 

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import glob
from libs.datasets import coco
import libs.preprocessings.coco_v1 as coco_preprocess

def get_dataset(dataset_name, split_name, dataset_dir, 
        im_batch=1, is_training=False, file_pattern=None, reader=None):
    """"""
    if file_pattern is None:
        #file_pattern = dataset_name + '_' + split_name + '*.tfrecord' 
        file_pattern = '/home/daxika/FastMaskRCNN-master/data/coco/' + '*' 
    temp = file_pattern
    tfrecords = glob.glob(temp)
    # tfrecords = glob.glob(dataset_dir + '/records/' + file_pattern)
    image, ih, iw, gt_boxes, gt_masks, num_instances, img_id = coco.read(tfrecords)

    image, gt_boxes, gt_masks = coco_preprocess.preprocess_image(image, gt_boxes, gt_masks, is_training)

    return image, ih, iw, gt_boxes, gt_masks, num_instances, img_id

**Comment by realwecan** [comment]
Same error here I think it is the working directory. No need to specify an absolute path.

**Comment by pwccc1990** [comment]
take the train.py under the directory FastMaskRCNN-master could solve the error
