### ISSUE TITLE
CUDA Libraries

### ISSUE THREAD

**Issue by davogt** [CharlesShang/FastMaskRCNN#81]
EnvironmentError: The CUDA lib64 path could not be located in /usr/lib64

in file ./libs/setup.py lib64 is set as path

**Comment by petrbela** [comment]
CUDA is typically installed in `/usr/local/cuda`, so the lib64 path should be `/usr/local/cuda/lib64`.

**Comment by davogt** [comment]
@petrbela thanks for your response. Excuse me for not pointing out the problem exactly, the installation paths are just as you mentioned.
making the following changes in ./libs/setup.py did the trick.
cudaconfig = {'home':home, 'nvcc':nvcc,
                  'include': pjoin(home, 'include'),
                  'lib64': pjoin(home, 'lib')}

**Comment by petrbela** [comment]
@davogt If your problem is fixed, would you mind closing the issue?
