### ISSUE TITLE
Sharing the weights of 190K epcohs

### ISSUE THREAD

**Issue by abduallahmohamed** [CharlesShang/FastMaskRCNN#89]
Here's the weights of 190K epochs, 
https://drive.google.com/file/d/0BwVrmnQ5PwycT0p1Y0tLQV9UYUk/view?usp=sharing

It took me around 3 days training  on Nvidia K80 GPU.

**Comment by BeipengMu** [comment]
Did you test it? Does the weights make sense?

**Comment by bhattad2** [comment]
Weights of 500K was share couple of days back!
https://github.com/CharlesShang/FastMaskRCNN/issues/86#issuecomment-309022377

**Comment by abduallahadel** [comment]
@BeipengMu  No, I'm not fluent enough in tensorflow in order to write down a test code...

**Comment by imyourm8** [comment]
Thanks for sharing, but can u share file named 'checkpoint' as well?

**Comment by XieSufe** [comment]
@abduallahadel Thanks for sharing, but I got an Error when running the '190KEPOCH' result. My code is:

> tf.reset_default_graph()
> checkpoint_dir = "G:\\\\190KEPOCH\\\\"  
> meta_file_path = checkpoint_dir + "coco_resnet50_model.ckpt-190000.meta"  
> ckpt_file_path = checkpoint_dir + "coco_resnet50_model.ckpt-190000"  
> new_saver = tf.train.import_meta_graph(meta_file_path)

Then comes the error:

> Traceback (most recent call last):
> 
>   File "<ipython-input-4-2fdc3db59c64>", line 1, in <module>
>     new_saver = tf.train.import_meta_graph(meta_file_path)
> 
>   File "D:\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1526, in import_meta_graph
>     **kwargs)
> 
>   File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\meta_graph.py", line 502, in import_scoped_meta_graph
>     producer_op_list=producer_op_list)
> 
>   File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\importer.py", line 258, in import_graph_def
>     op_def = op_dict[node.op]
> 
> KeyError: 'VariableV2'`

Who can please help me with it? Thanks a lot.
