### ISSUE TITLE
All class predictions are for class #0

### ISSUE THREAD

**Issue by realwecan** [CharlesShang/FastMaskRCNN#94]
Has anyone examined the output of the trained model on COCO? I tried but it seems all predictions belong to class #0...

**Comment by JackLongKing** [comment]
@realwecan Could you tell me how to test the model(the details) ?

**Comment by HuangBo-Terraloupe** [comment]
Hello @realwecan ,

If it is fine, can you please share the code you do prediction? I mean get the output of trained model.

**Comment by realwecan** [comment]
@JackLongKing @HuangBo-Terraloupe I just checked the values of cls2_prob in pyramid_network.py and found the class outputs all belong to class #0. Will try to figure this out, write the evaluation codes, and then share them here. Would appreciate if anyone could share some thoughts or suggestions...
